on: [ pull_request ]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...  -coverprofile fmtcoverage.html fmt && go tool cover -html=fmtcoverage.html -o coverage.html

      - name: Coverage artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: |
            fmtcoverage.html
            coverage.html

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          skip-go-installation: true
          args: --issues-exit-code=0 # Игнорим ошибки, фиксить буду в рамках рефакторинга
          working-directory: internal